default:
  target: postgres
  outputs:
    postgres:
      type: postgres
      host: db-postgresql-nyc1-37875-do-user-12598274-0.b.db.ondigitalocean.com
      user: doadmin
      pass: AVNS_5VO5B5DPycLrTBglKRr
      port: 25060
      threads: 4
      dbname: defaultdb
      schema: featuredata3405_scratch